import Navbar from '@/components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import App from './app'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Products',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <App>
          <Navbar />
          <div className="flex justify-center place-items-center h-[calc(100vh-3rem)]">
            {children}
          </div>
        </App>
      </body>
    </html>
  )
}
