import Navbar from '@/components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import App from './_app'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Products',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <App>
        <body className={inter.className}>
            <Navbar />
            <div className="container mx-auto mt-10">
              {children}
            </div>
        </body>
      </App>
    </html>
  )
}
