'use client'

import Navbar from '@/components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Products management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <div className="container mx-auto mt-10">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
